### PR TITLE
Allow JARs to be easily added to the classpath

### PR DESCRIPTION
**Pull request by cjmamo**
- allow JARs to be easily added to the classpath
- remove duplicate JARs from executable
- describe how the database can be changed

### CODE REVIEW

**Review by sekiskylink — APPROVED** [review]

**Comment by bobjolliffe** [comment]
I see that you have added ./lib relative to the current working directory as a default.  Though it is not necessarily clear what is the current working directory.  Do you mean where the executable jar resides?  Or the directory from which the executable is called.  There is maybe room for some stronger explanation here.  By default we would normally like to see the executable running from something like /usr/local/bin/rapidproconnector.  Is it possible in such a case to set a classpath to everything under /usr/local/lib/rapidproconnector for example (obviously can be done with JAVA_OPTS.  Or perhaps spring config)

**Comment by claudemamo** [comment]
> Do you mean where the executable jar resides? Or the directory from which the executable is called.

I realised it's actually both after some experimentation. It's the latter when run with `java -jar` but the former when run with `./dhis2rapidpro.jar`. I'll have to clarify this in the documentation. 

> Is it possible in such a case to set a classpath to everything under /usr/local/lib/rapidproconnector for example

It's possible by overriding application's loader path in an environment variable: `export LOADER_PATH=/usr/local/lib/rapidproconnector`. Will document it.

**Comment by bobjolliffe** [comment]
Running it like ./dhis2rapidpro.jar is a bit ambiguous as the CWD will actually be the same as the directory of the executable.  If you run /usr/local/bin/dhis2rapidpro.jar from your home directory will it pick up classpath from /usr/local/bin/lib or from ~/lib ?

**Comment by claudemamo** [comment]
>If you run /usr/local/bin/dhis2rapidpro.jar from your home directory will it pick up classpath from /usr/local/bin/lib or from ~/lib ?

You mean like `./usr/local/bin/dhis2rapidpro.jar`? It will scan JARs in ` /usr/local/bin/lib`. If you ran it like `java -jar /usr/local/bin/dhis2rapidpro.jar` from your home directory, then it will scan JARs in `~/lib`.

**Pull request merged**
